[package]
name = "SmartHome-App-Config"
version = "0.1.0"
authors = ["andrei"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mosquitto-client = "0.1.5"